### ISSUE TITLE
DCH missing

### ISSUE THREAD

**Issue by airvb** [flightaware/piaware_builder#13]
Hello , 
During 3.6.3 building, just before the end :
```
patching file setup.py
patching file cx_Freeze/finder.py
Updating changelog for jessie backport build
./sensible-build.sh: ligne 103: dch : commande introuvable
```
As expected, works ok after installing 
devscripts

**Comment by resuna** [comment]
Possibly the dch alias for debchange is localization-dependent?

**Comment by mutability** [comment]
I don't think it's localization dependent.

dch is a build requirement, and a build requirement that exists before the package tree is even prepared (so the dependency can't be automated as part of debian/control), so this is just a documentation thing.
