### ISSUE TITLE
Allow for wifi-only config

### ISSUE THREAD

**Issue by jamesshannon** [flightaware/piaware_builder#2]
I hope this is the right project.

I just received my raspberry and SDRs and wifi dongle for the stratux box I'm building. I thought I'd put it to use as a piaware client in its downtime. I grabbed the zip file, put it on the sd card, and then realized that you don't have any sort of wifi-only config.

I don't have a wired network that I can plug non-certificate-ed machines into, and I don't have a HDMI cable and keyboard handy. Ideally, I'd be able to set up piaware without any of the above.

At it's most basic, it should provide a server that I can connect to and configure the wifi connection, then let it try to connect.

That can either be over ethernet (with a crossover cable, if you still need those these days) or a wifi network (e.g., piaware-config) that it sets up if a) it finds a wifi dongle and b) it does not have instructions to connect to a wifi network or c) it cannot connect to the wifi network which it has instructions to connect to.

Stratux does the above (at least with wifi... not sure about ethernet).

Once I'm connected, I can either SSH in or connect via a web browser and enter wifi config info.

**Comment by mutability** [comment]
This is not really a piaware (ie the feeder software) thing, it is more of
a sdcard image configuration thing. There is some stuff in progress to
support this type of install but it is probably at least a month away.

The initial approach is to provide a configuration file on the boot
partition of the image (which is FAT and can be easily accessed from
windows, OS X, etc) that lets you configure the network settings etc. I
think that handles your situation.

**Comment by mutability** [comment]
This is now handled with the piaware 3 sdcard image (more specifically, the piaware-support package: https://github.com/flightaware/piaware-support)
