### ISSUE TITLE
Documentation question

### ISSUE THREAD

**Issue by rromanchuk** [flightaware/piaware_builder#22]
Is the documentation living at https://flightaware.com/adsb/piaware/install still accurate? Suspicious due to the hardcoded versioning. 

```
wget https://flightaware.com/adsb/piaware/files/packages/pool/piaware/f/flightaware-apt-repository/flightaware-apt-repository_1.1_all.deb
sudo dpkg -i flightaware-apt-repository_1.1_all.deb
```

This repo doesn't support arm64, so trying to avoid building from source if there is already a distribution out there.

**Comment by mutability** [comment]
Yes, that's current.

FlightAware only currently supplies prebuilt packages for armhf, for arm64 you will need to build from source. (I'm working on making arm64 available but it's not there yet)
