### ISSUE TITLE
getting version error trying to install a clean piaware_builder dev version

### ISSUE THREAD

**Issue by jthawkes** [flightaware/piaware_builder#4]
Using username "pi".
pi@192.168.249.124's password:

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed Jul 27 17:34:33 2016 from 192.168.249.7
pi@tardis2:~ $ sudo rm -r piaware_builder/
pi@tardis2:~ $ git clone https://github.com/flightaware/piaware_builder.git -b ev
Cloning into 'piaware_builder'...
fatal: Remote branch ev not found in upstream origin
pi@tardis2:~ $ git clone https://github.com/flightaware/piaware_builder.git -b ev
Cloning into 'piaware_builder'...
fatal: Remote branch ev not found in upstream origin
pi@tardis2:~ $ git clone https://github.com/flightaware/piaware_builder.git -b dev
Cloning into 'piaware_builder'...
remote: Counting objects: 252, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 252 (delta 2), reused 0 (delta 0), pack-reused 245
Receiving objects: 100% (252/252), 56.78 KiB | 0 bytes/s, done.
Resolving deltas: 100% (153/153), done.
Checking connectivity... done.
pi@tardis2:~ $ cd pi
-bash: cd: pi: No such file or directory
pi@tardis2:~ $ cd piaware_builder/
pi@tardis2:~/piaware_builder $ ./sensible-build.sh jessie
Retrieving origin/dev from https://github.com/flightaware/piaware.git
Cloning into './package-jessie/piaware'...
remote: Counting objects: 2510, done.
remote: Total 2510 (delta 0), reused 0 (delta 0), pack-reused 2510
Receiving objects: 100% (2510/2510), 546.36 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1765/1765), done.
Checking connectivity... done.
1fd4d7f Release 3.0.2
Retrieving 460debe4d350f06f9c7e54e5400992cac4f1d328 from https://github.com/flightaware/tcllauncher.git
Cloning into './package-jessie/tcllauncher'...
remote: Counting objects: 430, done.
remote: Total 430 (delta 0), reused 0 (delta 0), pack-reused 430
Receiving objects: 100% (430/430), 260.33 KiB | 0 bytes/s, done.
Resolving deltas: 100% (235/235), done.
Checking connectivity... done.
460debe Update README.md
Retrieving origin/dev from https://github.com/flightaware/dump1090.git
Cloning into './package-jessie/dump1090'...
remote: Counting objects: 4926, done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 4926 (delta 15), reused 0 (delta 0), pack-reused 4894
Receiving objects: 100% (4926/4926), 6.02 MiB | 5.92 MiB/s, done.
Resolving deltas: 100% (3341/3341), done.
Checking connectivity... done.
e136f30 Release 3.0.2
Retrieving origin/dev from https://github.com/mutability/mlat-client.git
Cloning into './package-jessie/mlat-client'...
remote: Counting objects: 1064, done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 1064 (delta 11), reused 0 (delta 0), pack-reused 1035
Receiving objects: 100% (1064/1064), 316.50 KiB | 0 bytes/s, done.
Resolving deltas: 100% (693/693), done.
Checking connectivity... done.
84c8c8a Release 0.2.6
Retrieving and patching cxfreeze
2016-07-28 14:48:22 URL:https://pypi.python.org/packages/source/c/cx_Freeze/cx_Freeze-4.3.4.tar.gz [60172/60172] -> "-" [1]
patching file setup.py
Ok, package is ready to be built in ./package-jessie
run 'dpkg-buildpackage -b' there (or move it to a Pi and do so there, or use pbuilder, etc)
pi@tardis2:~/piaware_builder $ cd package-jessie/
pi@tardis2:~/piaware_builder/package-jessie $ dpkg-buildpackage -b
dpkg-buildpackage: source package piaware
dpkg-buildpackage: source version 3.0.2~dev
dpkg-buildpackage: source distribution UNRELEASED
dpkg-buildpackage: source changed by Oliver Jowett oliver@mutability.co.uk
dpkg-buildpackage: host architecture armhf
 dpkg-source --before-build package-jessie
 fakeroot debian/rules clean
dh clean --with=systemd
   dh_testdir
   debian/rules override_dh_auto_clean
make[1]: Entering directory '/home/pi/piaware_builder/package-jessie'
dh_auto_clean -D tcllauncher
dh_auto_clean -D dump1090
        cd dump1090
        make -j1 clean
make[2]: Entering directory '/home/pi/piaware_builder/package-jessie/dump1090'
rm -f _.o compat/clock_gettime/_.o compat/clock_nanosleep/_.o dump1090 view1090 faup1090 cprtests crctests
make[2]: Leaving directory '/home/pi/piaware_builder/package-jessie/dump1090'
        cd /home/pi/piaware_builder/package-jessie
cd mlat-client && /usr/bin/python3.4 setup.py clean -a
running clean
'build/lib.linux-armv7l-3.4' does not exist -- can't clean it
'build/bdist.linux-armv7l' does not exist -- can't clean it
'build/scripts-3.4' does not exist -- can't clean it
rm -fr /home/pi/piaware_builder/package-jessie/debian/venv
dh override_dh_auto_clean --with=systemd
make[1]: Leaving directory '/home/pi/piaware_builder/package-jessie'
   dh_clean
        rm -f debian/piaware.substvars
        rm -f debian/piaware._.debhelper
        rm -rf debian/piaware/
        rm -f debian/_.debhelper.log
        rm -f debian/files
        find .  ( ( \
                ( -path .\_/.git -o -path .*/.svn -o -path .*/.bzr -o -path .*/.hg -o -path .*/CVS ) -prune -o -type f -a \
                ( -name '#_#' -o -name '._~' -o -name '_~' -o -name DEADJOE \
                 -o -name '_.orig' -o -name '_.rej' -o -name '_.bak' \
                 -o -name '._.orig' -o -name ._.rej -o -name '.SUMS' \
                 -o -name TAGS -o ( -path '_/.deps/_' -a -name '*.P' ) \
                ) -exec rm -f {} + ) -o \
                ( -type d -a -name autom4te.cache -prune -exec rm -rf {} + ) )
        rm -f *-stamp
 debian/rules build
dh build --with=systemd
   dh_testdir
   debian/rules override_dh_auto_configure
make[1]: Entering directory '/home/pi/piaware_builder/package-jessie'
debian/check_versions

Version mismatch:

  debian/changelog (copied from piaware_builder/changelog) has latest version: 3.0.2~dev
    after stripping any backports suffix, it is version: 3.0.2~dev
  piaware/programs/piaware/config.tcl has piawareVersionFull set to: 3.0.2

Please fix this so the versions match and rebuild.

debian/rules:36: recipe for target 'check_versions' failed
make[1]: **\* [check_versions] Error 1
make[1]: Leaving directory '/home/pi/piaware_builder/package-jessie'
debian/rules:83: recipe for target 'build' failed
make: **\* [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
pi@tardis2:~/piaware_builder/package-jessie $ dpkg-buildpackage -b^C
pi@tardis2:~/piaware_builder/package-jessie $

**Comment by mutability** [comment]
Oops, forgot to push my final release changes. Should be fixed now.
